import { TableColumnEntity } from '../../core/entities/table-column.entity';

export const hospitalizations = {
  numberHistory: new TableColumnEntity({
    title: '№ ИБ стац.',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 0,
    sortKey: 'numberHistory',
  }),
  patient: new TableColumnEntity({
    title: 'ФИО',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 1,
    sortKey: 'patient',
  }),
  ambulatoryCardId: new TableColumnEntity({
    title: '№ АК',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 2,
    sortKey: 'ambulatoryCardId',
  }),
  dateBegin: new TableColumnEntity({
    title: 'Дата начала',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 3,
    sortKey: 'dateBegin',
  }),
  dateEnd: new TableColumnEntity({
    title: 'Дата окончания',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 4,
    sortKey: 'dateEnd',
  }),
  payerCategory: new TableColumnEntity({
    title: 'Категория',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 5,
    sortKey: 'payerCategory',
  }),
  doctor: new TableColumnEntity({
    title: 'Лечащий врач',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 6,
    sortKey: 'doctor',
  }),
  department: new TableColumnEntity({
    title: 'Отделение',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 7,
    sortKey: 'department',
  }),
  profile: new TableColumnEntity({
    title: 'Профиль',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 8,
    sortKey: 'profile',
  }),
  status: new TableColumnEntity({
    title: 'Статус',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 9,
    sortKey: 'status',
  }),
  ward: new TableColumnEntity({
    title: 'Палата',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 10,
    sortKey: 'ward',
  }),
  place: new TableColumnEntity({
    title: 'Место',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 11,
    sortKey: 'place',
  }),
  diagnosis: new TableColumnEntity({
    title: 'Диагноз',
    isSortable: true,
    flexFactor: 2,
    view: true,
    position: 12,
    sortKey: 'diagnosis',
  }),
  birthday: new TableColumnEntity({
    title: 'Дата рождения',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 13,
    sortKey: 'birthday',
  }),
  age: new TableColumnEntity({
    title: 'Возр.',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 14,
    sortKey: 'age',
  }),
  bedDays: new TableColumnEntity({
    title: 'Койко-дни',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 15,
    sortKey: 'bedDays',
  }),
  result: new TableColumnEntity({
    title: 'Результат госпитализации',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 16,
    sortKey: 'result',
  }),
  gender: new TableColumnEntity({
    title: 'Пол',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 17,
    sortKey: 'gender',
  }),
  verifyStatus: new TableColumnEntity({
    title: 'Статус проверки',
    isSortable: true,
    flexFactor: 1,
    view: true,
    position: 19,
    sortKey: 'verifyStatus',
  }),
};
